title: Logan Bray
logo: Profile.png
description: Dedicated and analytical professional with a strong background in data analysis and communication seeking a Business Analyst position to leverage expertise in optimizing business operations and decision-making processes.
show_downloads: true
theme: jekyll-theme-minimal
